# jpge — Minimal public domain/Apache-2.0 baseline JPEG encoder (single file)
# Vendored from https://github.com/richgel999/jpeg-compressor (commit master 2024).
# Dual-licensed: public domain (license 1) or Apache-2.0 (license 2) — both
# GPL-3.0 compatible. Unmodified upstream sources; keep this copy pristine.
idf_component_register(SRCS "jpge.cpp"
                       INCLUDE_DIRS ".")
